### PR TITLE
Added comment tokens.

### PR DESCRIPTION
**Pull request by SirBogman**

### CODE REVIEW

**Comment by SirBogman** [comment]
This will support the new Ctrl + / command on Code Golf to toggle line comments.

**Comment by NewDefectus** [comment]
Is there a way to make this command position-dependent? Because preferably the line comment token would change to ; (a semicolon) when the cursor is in an area marked as Intel-syntax and to # when it's marked as AT&T-syntax

**Comment by SirBogman** [comment]
That's a good question, I can look into it.

**Comment by SirBogman** [comment]
I think there is, although I'm not sure how to set up the data.

https://codemirror.net/examples/mixed-language/

> CodeMirror's [languageDataAt](https://codemirror.net/docs/ref/#state.EditorState.languageDataAt) feature can be used to look up values associated with the language active at a given point in the document. If you define things like autocompletion using this mechanism, it will automatically look up the proper completion source in a mixed-language document.

**Comment by SirBogman** [comment]
I will try to find out more info.

**Comment by NewDefectus** [comment]
I just added a facet that adds the language data at the given position (61ce5d4), it should work with the languageDataAt function. I'll push a new patch in a sec

**Comment by SirBogman** [comment]
Thanks for implementing this.

**Pull request closed without merging**
